spring.application.name=projetJEE
<<<<<<< HEAD
server.port=8082
spring.mongodb.uri=mongodb://localhost:27017/projet
=======
server.port=9090
spring.data.mongodb.uri=mongodb://localhost:27017/test
>>>>>>> origin/farah
spring.data.mongodb.auto-index-creation=true