spring.application.name=projetJEE
server.port=9090

# MongoDB configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=projet
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.uri=mongodb://localhost:27017/projet

# Disable default datasource configuration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration